export const alias = {
  bash: ['bash', 'sh', 'zsh', 'ksh', 'fish', 'shell', 'unix', 'command'],
  c: ['c', 'h'],
  cpp: ['cpp', 'cc', 'c++', 'h++', 'hpp', 'hh', 'hxx', 'cxx'],
  csharp: ['chasp', 'cs', 'c#'],
  css: ['css'],
  erlang: ['erlang', 'erl'],
  elixir: ['elixir', 'ex', 'exs'],
  go: ['go', 'golang'],
  handlebars: ['handlebars', 'hbs', 'html.hbs', 'html.handlebars', 'htmlbars'],
  haskell: ['haskell', 'hs'],
  ini: ['ini', 'toml'],
  java: ['java', 'jsp'],
  javascript: ['javascript', 'js', 'jsx', 'mjs', 'cjs'],
  json: ['json'],
  kotlin: ['kotlin', 'kt', 'kts'],
  lisp: ['lisp'],
  lua: ['lua'],
  makefile: ['makefile', 'mk', 'mak', 'make'],
  markdown: ['markdown', 'md', 'mkdown', 'mkd'],
  matlab: ['matlab'],
  objectivec: ['objectivec', 'mm', 'objc', 'obj-c', 'obj-c++', 'objective-c++'],
  perl: ['perl', 'pl', 'pm'],
  php: ['php'],
  python: ['python', 'py', 'gyp', 'ipython'],
  r: ['r'],
  ruby: ['ruby', 'rb', 'gemspec', 'podspec', 'thor', 'irb'],
  rust: ['rust', 'rs'],
  scss: ['scss'],
  sql: ['sql'],
  swift: ['swift'],
  twig: ['twig', 'craftcms'],
  typescript: ['typescript', 'ts', 'tsx'],
  xml: ['xml', 'html', 'xhtml', 'rss', 'atom', 'xjb', 'xsd', 'xsl', 'plist', 'wsf', 'svg'],
  yaml: ['yaml', 'yml']
};
